#spring.application.name=governance-engine
## Database Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/your_db_name
#spring.datasource.username=postgres
#spring.datasource.password=aigoverence10
#
## JPA / Hibernate Settings
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## Performance Optimization (Java 21 Feature)
#spring.threads.virtual.enabled=true

# Supabase Cloud Connection Settings
spring.datasource.url=jdbc:postgresql://db.jlkfqpmrnvoxivnfbhhf.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=aigoverence10
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
# Use 'update' so Hibernate doesn't delete your tables but creates missing ones
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Connection Pooling for Team Stability
spring.datasource.hikari.maximum-pool-size=5